default : GameAction.class InputManager.class

clean :
	@rm -f ./*.class

GameAction.class : GameAction.java
	@javac -cp ../../../ GameAction.java

InputManager.class : InputManager.java
	@javac -cp ../../../ InputManager.java
